<TaskListScreen>:
    MDBoxLayout:
        orientation: "vertical"
        spacing: "20sp"
        MDBottomAppBar:
            md_bg_color: 0, 1, 0, 1
            MDTopAppBar:
                title: "Title"
                icon: "git"
                type: "bottom"
                left_action_items: [["menu", lambda x: x]]
                on_action_button: app.callback(self.icon)
                mode: "end"
                icon_color: 0, 0, 0, 1